name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: specify-tag
      run: git describe HEAD --tags
    - name: get-tag-name
      uses: olegtarasov/get-tag@v2
      id: tagName
    - run: echo ${GIT_TAG_NAME}
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.ROBOT_NAME }}
        password: ${{ secrets.ROBOT_PASS }}
        registry: quay.io
        repository: deuspro/hello-app
        tag_with_ref: true
