name: Build test
on:
  push:
    branches-ignore:
    - 'master'
env:
  GKE_CLUSTER: dojo-gke-cluster
  GKE_ZONE: us-central1
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: specify-tag
      run: echo "::set-env name=TAG::$(git describe HEAD --tags)"
    - run: echo ${TAG}
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        build_args: TAG=${{ env.TAG }}
        username: ${{ secrets.ROBOT_NAME }}
        password: ${{ secrets.ROBOT_PASS }}
        registry: quay.io
        repository: deuspro/hello-app
        tags: ${{ env.TAG }}
    - name: install helm
      uses: azure/setup-helm@v1
    - name: bake a helm package
      run: helm package --app-version ${{ env.TAG }} --version ${{ env.TAG }} ./deployments/helm/hello-app/
    - name: Setup gcloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_DEVELOPER }}
        project_id: ${{ secrets.GKE_PROJECT }}
    - name: Authenticate in k8s
      run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}
    - name: deploy to k8s
      uses: 'deliverybot/helm@v1'
      with:
        release: hello-app
        namespace: hello
        chart: "/home/runner/work/hello-app/hello-app/hello-app-${{ env.TAG }}.tgz"
